pipelines:
  default:
    - parallel:
        - step:
            name: Build & Test 2.7
            image: python:2.7
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 3.3
            image: python:3.3
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 3.4
            image: python:3.4
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 3.5
            image: python:3.5
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 3.6
            image: python:3.6
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
        - step:
            name: Build & Test 3.7-rc
            image: python:3.7-rc
            script:
              - python setup.py sdist
              - pip install -f dist assemblyline_client .[test]
              - pytest
